{% set name = "opt_einsum" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96ca72f1b886d148241348783498194c577fa30a8faac108586b14f1ba4473ac

build:
  noarch: python
  number: 0

outputs:
  - name: opt_einsum
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - python >=3.8
        - hatchling
        - hatch-fancy-pypi-readme
        - hatch-vcs
      run:
        - python >=3.8
    test:
      requires:
        - python >=3.8
        - pytest
        - pip
      commands:
        - pytest --pyargs opt_einsum
        - pip check
      imports:
        - opt_einsum

  - name: opt-einsum
    build:
      noarch: generic
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
      run:
        - {{ pin_subpackage('opt_einsum', max_pin="x.x.x") }}
    test:
      imports:
        - opt_einsum

about:
  home: http://github.com/dgasmith/opt_einsum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optimizing einsum functions in NumPy, Tensorflow, Dask, and more with contraction order optimization.

  description: >
    Einsum is a very powerful function for contracting tensors of arbitrary dimension and index. However, it is typically only optimized to contract two terms at a time resulting in non-optimal scaling. This package optimizes the contraction order for arbitrarily large speedups.

    See the docs for more information: dgasmith.github.io/opt_einsum/

  dev_url: https://github.com/dgasmith/opt_einsum

extra:
  recipe-maintainers:
    - dgasmith
    - loriab
    - xhochy
    - pavelzw
