appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: f9PTWYZ0CsDmqLNQbUOfVqgFCuOaOFHMmxjjDBqKop3YeegkWRjYpYVKosifUt0BAX4g0yFxLjTnBhdpORdHzn/85mekA23OIs3upfkXvD3Vszn6bAUqaMW1HfhvLfGjzhXbEqpOLgWopWMJvDk+fDVevIQjAaabQG77leMeNW0+vNxw0QkYsben+X/QOq4ZgrtL44y1HEASfwfXuvkYwkutT/lPAJ0yNSMj8S95nRtEFgDT13NDQS8zM9Zjqb06pASIu45KdK0lLU+M3b14zXIAxhveJAbnlgCBnAsI3C66VJGgjf6W119CLb4HWAR9u04RpcTpSJ45HydVFr6oz++VcyWZDwrh5/YzZkEAxoBWvJrjfBPNJSWsfIEKaaHyJMxW3WMeWaBBgpBdYeeCB5rByRDlfToMev6HPJujzk8GtoxC1v4Kho1VmIjgnnyoZMtp8rATTaQ2dxUFpSrtOt9gIBTfiQMltkbpDmKPzdC/8enkwtnpX50tuBmRfUrMMnE6EPiAbPYcgcSbT6ZQR8/VnKGZSmuCDkDDGj2lyWUgYNFBUGudE1vHWSX8THwPFX4zDryTDD4YB1C9qSWvNBWejLMhjf/fquRYcoUz8R815xqFsVCCcoyn27yRDxZpUsAmr3d0EPMbjPIu8hD+GlBQfm77XJW6RByelRROfBs=}
provider:
  win: azure
conda_forge_output_validation: true
